### ISSUE TITLE
Cannot launch app

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#306]
@intrications App crashes at startup for commit 8715a6e523b817dbd013177b92580d6eb2ff724d

**Comment by intrications** [comment]
@libreliodev 

I probably need a stacktrace. It's working for me on multiple devices even after an uninstall.

What device is this on? Or emulator?

**Comment by libreliodev** [comment]
This is on 2 different devices. Maybe something went wrong with compilation. The version I am trying to install is on Dropbox at the usual place

**Comment by intrications** [comment]
The APK isn't crashing for me but it also isn't showing any magazines.

I am investigating.

**Comment by intrications** [comment]
@libreliodev The APK in Dropbox is not crashing for me. I will require a stacktrace.

**Comment by intrications** [comment]
@libreliodev 

Sorry, I forgot that the Dropbox folder wasn't updated with the latest files. Should work now.

**Comment by libreliodev** [comment]
@intrications 

Sorry, it still does not work, but I also don't seen any update in Dropbox from you. Can you make sure you have updated it. Alternatively, can push the content of your Dropbox folder to num/android in https://github.com/libreliodev/client-customizations

**Comment by intrications** [comment]
@libreliodev 

Sorry, hadn't noticed that Dropbox hadn't restarted.

Syncing now, but on train so may take a little time.

**Comment by libreliodev** [comment]
@intrications 

Built a new version based on the latest Dropbox contents. This new version worked on an old Galaxy Tab, but crashed on 2 other devices. Any idea why?

**Comment by intrications** [comment]
Not without a stacktrace.

Although it may pushing crash reports to Crashlytics. I will check.

**Comment by libreliodev** [comment]
Thanks.
What method do you recommend to get the stack trace? adb?

**Comment by intrications** [comment]
Yes, adb. I don't see the crashes in Crashlytics yet.

**Comment by libreliodev** [comment]
Does this help?
```
04-21 23:10:16.531 I/ActivityManager(  941): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.numero.numero/com.librelio.activity.StartupActivity (has extras)} from uid 10028 on display 0
04-21 23:10:16.532 V/msm8974_platform(  294): platform_get_output_snd_device: enter: output devices(0x2)
04-21 23:10:16.532 V/msm8974_platform(  294): platform_get_output_snd_device: exit: snd_device(speaker)
04-21 23:10:16.532 D/audio_hw_primary(  294): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
04-21 23:10:16.532 D/hardware_info(  294): hw_info_append_hw_type : device_name = speaker
04-21 23:10:16.532 V/msm8974_platform(  294): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
04-21 23:10:16.543 E/msm8974_platform(  294): platform_update_tpa_poll: Could not get ctl for mixer cmd - TPA6165 POLL ACC DET
04-21 23:10:16.549 W/ContextImpl( 1728): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
04-21 23:10:16.682 I/ActivityManager(  941): Start proc com.numero.numero for activity com.numero.numero/com.librelio.activity.StartupActivity: pid=20171 uid=10147 gids={50147, 9997, 3003, 1028, 1015} abi=armeabi-v7a
04-21 23:10:16.708 I/art     (  317): Explicit concurrent mark sweep GC freed 709(30KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/11MB, paused 240us total 24.616ms
04-21 23:10:16.737 I/art     (  317): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/11MB, paused 267us total 26.010ms
04-21 23:10:16.759 I/art     (  317): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/11MB, paused 258us total 21.180ms
04-21 23:10:16.766 W/ContextImpl( 1728): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
04-21 23:10:16.996 I/GooglePlayServicesUtils(20171): Registration not found.
04-21 23:10:17.247 I/SFPerfTracer(  278):      triggers: (rate: 2669:84826) (compose: 0:145) (post: 0:29) (render: 83:2521) (4:1201472 frames) (5:1281134)
04-21 23:10:17.247 D/SFPerfTracer(  278):        layers: (4:10) (FocusedStackFrame (0xb715ab80): 0:5556)* (DimLayer (0xb71625c8): 0:449)* (DimLayer (0xb7164338): 0:21)* (StatusBar (0xb720f2b0): 3:66530)* (DimLayer (0xb71f7c28): 0:4427)* (DimLayer (0xb71d63b8): 0:1553)* (com.android.systemui.ImageWallpaper (0xb7213bf8): 0:13502) (NavigationBar (0xb720b150): 0:49) (com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (0xb71d2e70): 0:282) (Starting com.numero.numero (0xb71d4100): 5:11) 
04-21 23:10:17.304 I/art     (20171): Background sticky concurrent mark sweep GC freed 6438(414KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 11MB/11MB, paused 5.988ms total 48.214ms
04-21 23:10:17.347 I/art     (  941): Explicit concurrent mark sweep GC freed 86710(4MB) AllocSpace objects, 22(825KB) LOS objects, 31% free, 35MB/51MB, paused 2.232ms total 266.692ms
04-21 23:10:17.382 D/GCM     (16241): COMPAT: Multi user ser=0 current=0
04-21 23:10:17.402 W/ResourcesManager(20171): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
04-21 23:10:17.402 W/ResourcesManager(20171): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
04-21 23:10:17.720 I/WebViewFactory(20171): Loading com.google.android.webview version 40 (1832189-arm) (code 424501)
04-21 23:10:17.756 I/dex2oat (20212): /system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=div --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --dex-file=/data/data/com.numero.numero/cache/ads1574128204.jar --oat-fd=21 --oat-location=/data/data/com.numero.numero/cache/ads1574128204.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
04-21 23:10:17.918 I/LibraryLoader(20171): Time to load native libraries: 113 ms (timestamps 7104-7217)
04-21 23:10:17.918 I/LibraryLoader(20171): Expected native library version number "",actual native library version number ""
04-21 23:10:17.936 I/SBar.MotoNetworkCtrlr( 1575): updateDataNetType[1]: phoneId1 is not DDS( =phoneId0 ) ! -- Set all data icons to off ( SubscriptionManager.getPhoneId returned 0=0x00000000 )
04-21 23:10:17.960 V/WebViewChromiumFactoryProvider(20171): Binding Chromium to main looper Looper (main, tid 1) {27145dad}
04-21 23:10:17.960 I/LibraryLoader(20171): Expected native library version number "",actual native library version number ""
04-21 23:10:17.961 I/chromium(20171): [INFO:library_loader_hooks.cc(108)] Chromium logging enabled: level = 0, default verbosity = 0
04-21 23:10:17.980 I/BrowserStartupController(20171): Initializing chromium process, singleProcess=true
04-21 23:10:17.987 W/art     (20171): Attempt to remove local handle scope entry from IRT, ignoring
04-21 23:10:18.020 W/AudioManagerAndroid(20171): Requires BLUETOOTH permission
04-21 23:10:18.050 W/chromium(20171): [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
04-21 23:10:18.051 I/chromium(20171): [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=32 off=76420 len=4033
04-21 23:10:18.052 I/chromium(20171): [INFO:aw_browser_main_parts.cc(76)] Loading webviewchromium.pak from, fd:33 off:390788 len:1143511
04-21 23:10:18.070 I/Adreno-EGL(20171): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107_msm8226_LA.BF.1.1__release_AU ()
04-21 23:10:18.070 I/Adreno-EGL(20171): OpenGL ES Shader Compiler Version: E031.25.01.03
04-21 23:10:18.070 I/Adreno-EGL(20171): Build Date: 10/28/14 Tue
04-21 23:10:18.070 I/Adreno-EGL(20171): Local Branch: 
04-21 23:10:18.070 I/Adreno-EGL(20171): Remote Branch: quic/l_LNX.LA.3.6
04-21 23:10:18.070 I/Adreno-EGL(20171): Local Patches: NONE
04-21 23:10:18.070 I/Adreno-EGL(20171): Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107 + cb93e16 + f50fe49 + d7c18e6 + 5b9a565 + 0f3a25d + 607156e + 75511aa + e4d16c0 + 686f3eb + 211a271 + dd281ee +  NOTHING
04-21 23:10:18.095 I/dex2oat (20212): dex2oat took 332.899ms (threads: 4)
04-21 23:10:18.177 I/Ads     (20171): Starting ad request.
04-21 23:10:18.180 I/Ads     (20171): Use AdRequest.Builder.addTestDevice("2E59359FAD3BBFBA9490F5DDC3A77AB2") to get test ads on this device.
04-21 23:10:18.224 D/AndroidRuntime(20171): Shutting down VM
04-21 23:10:18.230 E/AndroidRuntime(20171): FATAL EXCEPTION: main
04-21 23:10:18.230 E/AndroidRuntime(20171): Process: com.numero.numero, PID: 20171
04-21 23:10:18.230 E/AndroidRuntime(20171): java.lang.RuntimeException: Unable to resume activity {com.numero.numero/com.librelio.activity.StartupActivity}: de.greenrobot.event.EventBusException: Subscriber class com.librelio.activity.StartupActivity has no public methods called onEvent
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2995)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3030)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2393)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread.access$800(ActivityThread.java:148)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.os.Looper.loop(Looper.java:135)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread.main(ActivityThread.java:5312)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at java.lang.reflect.Method.invoke(Native Method)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
04-21 23:10:18.230 E/AndroidRuntime(20171): Caused by: de.greenrobot.event.EventBusException: Subscriber class com.librelio.activity.StartupActivity has no public methods called onEvent
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:119)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at de.greenrobot.event.EventBus.register(EventBus.java:163)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at de.greenrobot.event.EventBus.register(EventBus.java:133)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at com.librelio.base.BaseActivity.onResume(BaseActivity.java:191)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1264)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.Activity.performResume(Activity.java:6039)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2978)
04-21 23:10:18.230 E/AndroidRuntime(20171): 	... 11 more
04-21 23:10:18.241 W/ActivityManager(  941):   Force finishing activity com.numero.numero/com.librelio.activity.StartupActivity
04-21 23:10:18.542 I/WindowManager(  941): Screenshot max retries 4 of Token{29521fda ActivityRecord{1da55585 u0 com.numero.numero/com.librelio.activity.StartupActivity t294 f}} appWin=Window{3aeac501 u0 Starting com.numero.numero} drawState=4
04-21 23:10:18.543 E/ActivityManager(  941): Invalid thumbnail dimensions: 384x384
04-21 23:10:18.545 W/ContextImpl( 1728): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1455 android.content.ContextWrapper.sendBroadcast:376 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
04-21 23:10:18.601 I/OpenGLRenderer(  941): Initialized EGL, version 1.4
```

**Comment by intrications** [comment]
Please try the latest commit.

**Comment by libreliodev** [comment]
@intrications Latest commit no longer crashes on device where it did.
Thanks.

**Comment by libreliodev** [comment]
@intrications I can again no longer build the app, could this be related to Dropbox not being synced?

**Comment by intrications** [comment]
@libreliodev I think you've probably noticed that I just updated the Dropbox files.

**Comment by libreliodev** [comment]
OK, thanks.
